/* automatically generated by rust-bindgen 0.72.1 */

pub const BOOL_FALSE: BOOL = 0;
pub const BOOL_TRUE: BOOL = 1;
pub type BOOL = ::std::os::raw::c_uint;
pub const Ordertype_NOT_COMPARABLE: Ordertype = 0;
pub const Ordertype_SAME_AS: Ordertype = 1;
pub const Ordertype_LESS_THAN: Ordertype = 2;
pub const Ordertype_GREATER_THAN: Ordertype = 3;
pub const Ordertype_LESS_THAN_OR_SAME_AS: Ordertype = 4;
pub const Ordertype_GREATER_THAN_OR_SAME_AS: Ordertype = 5;
pub const Ordertype_NOT_LESS_THAN: Ordertype = 6;
pub const Ordertype_NOT_GREATER_THAN: Ordertype = 7;
pub type Ordertype = ::std::os::raw::c_uint;
pub type Plist = *mut plist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct plist {
    pub v: *mut ::std::os::raw::c_void,
    pub next: Plist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of plist"][::std::mem::size_of::<plist>() - 16usize];
    ["Alignment of plist"][::std::mem::align_of::<plist>() - 8usize];
    ["Offset of field: plist::v"][::std::mem::offset_of!(plist, v) - 0usize];
    ["Offset of field: plist::next"][::std::mem::offset_of!(plist, next) - 8usize];
};
pub type Ilist = *mut ilist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ilist {
    pub i: ::std::os::raw::c_int,
    pub next: Ilist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ilist"][::std::mem::size_of::<ilist>() - 16usize];
    ["Alignment of ilist"][::std::mem::align_of::<ilist>() - 8usize];
    ["Offset of field: ilist::i"][::std::mem::offset_of!(ilist, i) - 0usize];
    ["Offset of field: ilist::next"][::std::mem::offset_of!(ilist, next) - 8usize];
};
pub type I3list = *mut i3list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct i3list {
    pub i: ::std::os::raw::c_int,
    pub j: ::std::os::raw::c_int,
    pub k: ::std::os::raw::c_int,
    pub next: I3list,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of i3list"][::std::mem::size_of::<i3list>() - 24usize];
    ["Alignment of i3list"][::std::mem::align_of::<i3list>() - 8usize];
    ["Offset of field: i3list::i"][::std::mem::offset_of!(i3list, i) - 0usize];
    ["Offset of field: i3list::j"][::std::mem::offset_of!(i3list, j) - 4usize];
    ["Offset of field: i3list::k"][::std::mem::offset_of!(i3list, k) - 8usize];
    ["Offset of field: i3list::next"][::std::mem::offset_of!(i3list, next) - 16usize];
};
unsafe extern "C" {
    pub fn zap_ilist(p: Ilist);
}
unsafe extern "C" {
    pub fn str_to_sn(
        str_: *mut ::std::os::raw::c_char,
        arity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_lex_val(symnum: ::std::os::raw::c_int, lex_val: ::std::os::raw::c_int);
}
pub type Term = *mut term;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct term {
    pub private_symbol: ::std::os::raw::c_int,
    pub arity: ::std::os::raw::c_ushort,
    pub private_flags: ::std::os::raw::c_uchar,
    pub args: *mut Term,
    pub container: *mut ::std::os::raw::c_void,
    pub u: term__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union term__bindgen_ty_1 {
    pub id: ::std::os::raw::c_uint,
    pub vp: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of term__bindgen_ty_1"][::std::mem::size_of::<term__bindgen_ty_1>() - 8usize];
    ["Alignment of term__bindgen_ty_1"][::std::mem::align_of::<term__bindgen_ty_1>() - 8usize];
    ["Offset of field: term__bindgen_ty_1::id"]
        [::std::mem::offset_of!(term__bindgen_ty_1, id) - 0usize];
    ["Offset of field: term__bindgen_ty_1::vp"]
        [::std::mem::offset_of!(term__bindgen_ty_1, vp) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of term"][::std::mem::size_of::<term>() - 32usize];
    ["Alignment of term"][::std::mem::align_of::<term>() - 8usize];
    ["Offset of field: term::private_symbol"]
        [::std::mem::offset_of!(term, private_symbol) - 0usize];
    ["Offset of field: term::arity"][::std::mem::offset_of!(term, arity) - 4usize];
    ["Offset of field: term::private_flags"][::std::mem::offset_of!(term, private_flags) - 6usize];
    ["Offset of field: term::args"][::std::mem::offset_of!(term, args) - 8usize];
    ["Offset of field: term::container"][::std::mem::offset_of!(term, container) - 16usize];
    ["Offset of field: term::u"][::std::mem::offset_of!(term, u) - 24usize];
};
unsafe extern "C" {
    pub fn get_variable_term(var_num: ::std::os::raw::c_int) -> Term;
}
unsafe extern "C" {
    pub fn get_rigid_term(sym: *mut ::std::os::raw::c_char, arity: ::std::os::raw::c_int) -> Term;
}
unsafe extern "C" {
    pub fn zap_term(t: Term);
}
unsafe extern "C" {
    pub fn ground_term(t: Term) -> BOOL;
}
unsafe extern "C" {
    pub fn term_depth(t: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn symbol_count(t: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn occurs_in(t1: Term, t2: Term) -> BOOL;
}
unsafe extern "C" {
    pub fn term_to_string(t: Term) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn parse_term_from_string(s: *mut ::std::os::raw::c_char) -> Term;
}
pub type Context = *mut context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct context {
    pub terms: [Term; 100usize],
    pub contexts: [Context; 100usize],
    pub multiplier: ::std::os::raw::c_int,
    pub partial_term: Term,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of context"][::std::mem::size_of::<context>() - 1616usize];
    ["Alignment of context"][::std::mem::align_of::<context>() - 8usize];
    ["Offset of field: context::terms"][::std::mem::offset_of!(context, terms) - 0usize];
    ["Offset of field: context::contexts"][::std::mem::offset_of!(context, contexts) - 800usize];
    ["Offset of field: context::multiplier"]
        [::std::mem::offset_of!(context, multiplier) - 1600usize];
    ["Offset of field: context::partial_term"]
        [::std::mem::offset_of!(context, partial_term) - 1608usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct trail {
    _unused: [u8; 0],
}
pub type Trail = *mut trail;
unsafe extern "C" {
    pub fn get_context() -> Context;
}
unsafe extern "C" {
    pub fn free_context(p: Context);
}
unsafe extern "C" {
    pub fn unify(t1: Term, c1: Context, t2: Term, c2: Context, trp: *mut Trail) -> BOOL;
}
unsafe extern "C" {
    pub fn apply(t: Term, c: Context) -> Term;
}
unsafe extern "C" {
    pub fn undo_subst(tr: Trail);
}
pub const Indexop_INSERT: Indexop = 0;
pub const Indexop_DELETE: Indexop = 1;
pub type Indexop = ::std::os::raw::c_uint;
pub type Discrim = *mut discrim;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct discrim {
    pub next: Discrim,
    pub u: discrim__bindgen_ty_1,
    pub symbol: ::std::os::raw::c_int,
    pub type_: ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union discrim__bindgen_ty_1 {
    pub kids: Discrim,
    pub data: Plist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of discrim__bindgen_ty_1"][::std::mem::size_of::<discrim__bindgen_ty_1>() - 8usize];
    ["Alignment of discrim__bindgen_ty_1"]
        [::std::mem::align_of::<discrim__bindgen_ty_1>() - 8usize];
    ["Offset of field: discrim__bindgen_ty_1::kids"]
        [::std::mem::offset_of!(discrim__bindgen_ty_1, kids) - 0usize];
    ["Offset of field: discrim__bindgen_ty_1::data"]
        [::std::mem::offset_of!(discrim__bindgen_ty_1, data) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of discrim"][::std::mem::size_of::<discrim>() - 24usize];
    ["Alignment of discrim"][::std::mem::align_of::<discrim>() - 8usize];
    ["Offset of field: discrim::next"][::std::mem::offset_of!(discrim, next) - 0usize];
    ["Offset of field: discrim::u"][::std::mem::offset_of!(discrim, u) - 8usize];
    ["Offset of field: discrim::symbol"][::std::mem::offset_of!(discrim, symbol) - 16usize];
    ["Offset of field: discrim::type_"][::std::mem::offset_of!(discrim, type_) - 20usize];
};
pub type Discrim_pos = *mut discrim_pos;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct discrim_pos {
    pub query: *mut ::std::os::raw::c_void,
    pub subst: Context,
    pub data: Plist,
    pub backtrack: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of discrim_pos"][::std::mem::size_of::<discrim_pos>() - 32usize];
    ["Alignment of discrim_pos"][::std::mem::align_of::<discrim_pos>() - 8usize];
    ["Offset of field: discrim_pos::query"][::std::mem::offset_of!(discrim_pos, query) - 0usize];
    ["Offset of field: discrim_pos::subst"][::std::mem::offset_of!(discrim_pos, subst) - 8usize];
    ["Offset of field: discrim_pos::data"][::std::mem::offset_of!(discrim_pos, data) - 16usize];
    ["Offset of field: discrim_pos::backtrack"]
        [::std::mem::offset_of!(discrim_pos, backtrack) - 24usize];
};
unsafe extern "C" {
    pub fn discrim_init() -> Discrim;
}
unsafe extern "C" {
    pub fn destroy_discrim_tree(d: Discrim);
}
unsafe extern "C" {
    pub fn discrim_wild_update(
        t: Term,
        root: Discrim,
        object: *mut ::std::os::raw::c_void,
        op: Indexop,
    );
}
unsafe extern "C" {
    pub fn discrim_wild_retrieve_first(
        t: Term,
        root: Discrim,
        ppos: *mut Discrim_pos,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn discrim_wild_retrieve_next(pos: Discrim_pos) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn discrim_wild_cancel(pos: Discrim_pos);
}
pub type Literals = *mut literals;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct literals {
    pub sign: BOOL,
    pub atom: Term,
    pub next: Literals,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of literals"][::std::mem::size_of::<literals>() - 24usize];
    ["Alignment of literals"][::std::mem::align_of::<literals>() - 8usize];
    ["Offset of field: literals::sign"][::std::mem::offset_of!(literals, sign) - 0usize];
    ["Offset of field: literals::atom"][::std::mem::offset_of!(literals, atom) - 8usize];
    ["Offset of field: literals::next"][::std::mem::offset_of!(literals, next) - 16usize];
};
unsafe extern "C" {
    pub fn zap_literal(l: Literals);
}
unsafe extern "C" {
    pub fn zap_literals(l: Literals);
}
unsafe extern "C" {
    pub fn new_literal(sign: ::std::os::raw::c_int, atom: Term) -> Literals;
}
unsafe extern "C" {
    pub fn copy_literal(lit: Literals) -> Literals;
}
unsafe extern "C" {
    pub fn append_literal(lits: Literals, lit: Literals) -> Literals;
}
unsafe extern "C" {
    pub fn literal_to_term(l: Literals) -> Term;
}
unsafe extern "C" {
    pub fn literals_to_term(l: Literals) -> Term;
}
unsafe extern "C" {
    pub fn positive_literals(lits: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn negative_literals(lits: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn positive_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn negative_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn mixed_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn number_of_literals(lits: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn unit_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn horn_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn ground_clause(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn copy_literals(lits: Literals) -> Literals;
}
unsafe extern "C" {
    pub fn ith_literal(lits: Literals, i: ::std::os::raw::c_int) -> Literals;
}
unsafe extern "C" {
    pub fn tautology(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn clause_symbol_count(lits: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clause_depth(lits: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pos_eq(lit: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn neg_eq(lit: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn pos_eq_unit(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn neg_eq_unit(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn contains_pos_eq(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn contains_eq(lits: Literals) -> BOOL;
}
unsafe extern "C" {
    pub fn only_eq(lits: Literals) -> BOOL;
}
pub const Order_method_LRPO_METHOD: Order_method = 0;
pub const Order_method_LPO_METHOD: Order_method = 1;
pub const Order_method_RPO_METHOD: Order_method = 2;
pub const Order_method_KBO_METHOD: Order_method = 3;
pub type Order_method = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn assign_order_method(method: Order_method);
}
unsafe extern "C" {
    pub fn lrpo(s: Term, t: Term, lex_order_vars: BOOL) -> BOOL;
}
unsafe extern "C" {
    pub fn kbo(alpha: Term, beta: Term, lex_order_vars: BOOL) -> BOOL;
}
unsafe extern "C" {
    pub fn term_greater(alpha: Term, beta: Term, lex_order_vars: BOOL) -> BOOL;
}
unsafe extern "C" {
    pub fn term_order(alpha: Term, beta: Term) -> Ordertype;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct attribute {
    _unused: [u8; 0],
}
pub type Attribute = *mut attribute;
pub const Ftype_ATOM_FORM: Ftype = 0;
pub const Ftype_AND_FORM: Ftype = 1;
pub const Ftype_OR_FORM: Ftype = 2;
pub const Ftype_NOT_FORM: Ftype = 3;
pub const Ftype_IFF_FORM: Ftype = 4;
pub const Ftype_IMP_FORM: Ftype = 5;
pub const Ftype_IMPBY_FORM: Ftype = 6;
pub const Ftype_ALL_FORM: Ftype = 7;
pub const Ftype_EXISTS_FORM: Ftype = 8;
pub type Ftype = ::std::os::raw::c_uint;
pub type Formula = *mut formula;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct formula {
    pub type_: Ftype,
    pub arity: ::std::os::raw::c_int,
    pub qvar: *mut ::std::os::raw::c_char,
    pub kids: *mut Formula,
    pub atom: Term,
    pub attributes: Attribute,
    pub excess_refs: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of formula"][::std::mem::size_of::<formula>() - 48usize];
    ["Alignment of formula"][::std::mem::align_of::<formula>() - 8usize];
    ["Offset of field: formula::type_"][::std::mem::offset_of!(formula, type_) - 0usize];
    ["Offset of field: formula::arity"][::std::mem::offset_of!(formula, arity) - 4usize];
    ["Offset of field: formula::qvar"][::std::mem::offset_of!(formula, qvar) - 8usize];
    ["Offset of field: formula::kids"][::std::mem::offset_of!(formula, kids) - 16usize];
    ["Offset of field: formula::atom"][::std::mem::offset_of!(formula, atom) - 24usize];
    ["Offset of field: formula::attributes"][::std::mem::offset_of!(formula, attributes) - 32usize];
    ["Offset of field: formula::excess_refs"]
        [::std::mem::offset_of!(formula, excess_refs) - 40usize];
};
unsafe extern "C" {
    pub fn maximal_literal(lits: Literals, lit: Literals, check: ::std::os::raw::c_int) -> BOOL;
}
unsafe extern "C" {
    pub fn maximal_signed_literal(
        lits: Literals,
        lit: Literals,
        check: ::std::os::raw::c_int,
    ) -> BOOL;
}
unsafe extern "C" {
    pub fn number_of_maximal_literals(
        lits: Literals,
        check: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type Topform = *mut topform;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topform {
    pub id: ::std::os::raw::c_ulonglong,
    pub containers: *mut clist_pos,
    pub attributes: Attribute,
    pub justification: *mut just,
    pub weight: f64,
    pub compressed: *mut ::std::os::raw::c_char,
    pub matching_hint: Topform,
    pub last_matched_given: ::std::os::raw::c_ulonglong,
    pub proof_tree_weight_cache: ::std::os::raw::c_int,
    pub literals: Literals,
    pub formula: Formula,
    pub semantics: ::std::os::raw::c_int,
    pub is_formula: ::std::os::raw::c_char,
    pub normal_vars: ::std::os::raw::c_char,
    pub used: ::std::os::raw::c_char,
    pub official_id: ::std::os::raw::c_char,
    pub initial: ::std::os::raw::c_char,
    pub neg_compressed: ::std::os::raw::c_char,
    pub subsumer: ::std::os::raw::c_char,
    pub was_given: ::std::os::raw::c_char,
    pub goal_derived: ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topform"][::std::mem::size_of::<topform>() - 104usize];
    ["Alignment of topform"][::std::mem::align_of::<topform>() - 8usize];
    ["Offset of field: topform::id"][::std::mem::offset_of!(topform, id) - 0usize];
    ["Offset of field: topform::containers"][::std::mem::offset_of!(topform, containers) - 8usize];
    ["Offset of field: topform::attributes"][::std::mem::offset_of!(topform, attributes) - 16usize];
    ["Offset of field: topform::justification"]
        [::std::mem::offset_of!(topform, justification) - 24usize];
    ["Offset of field: topform::weight"][::std::mem::offset_of!(topform, weight) - 32usize];
    ["Offset of field: topform::compressed"][::std::mem::offset_of!(topform, compressed) - 40usize];
    ["Offset of field: topform::matching_hint"]
        [::std::mem::offset_of!(topform, matching_hint) - 48usize];
    ["Offset of field: topform::last_matched_given"]
        [::std::mem::offset_of!(topform, last_matched_given) - 56usize];
    ["Offset of field: topform::proof_tree_weight_cache"]
        [::std::mem::offset_of!(topform, proof_tree_weight_cache) - 64usize];
    ["Offset of field: topform::literals"][::std::mem::offset_of!(topform, literals) - 72usize];
    ["Offset of field: topform::formula"][::std::mem::offset_of!(topform, formula) - 80usize];
    ["Offset of field: topform::semantics"][::std::mem::offset_of!(topform, semantics) - 88usize];
    ["Offset of field: topform::is_formula"][::std::mem::offset_of!(topform, is_formula) - 92usize];
    ["Offset of field: topform::normal_vars"]
        [::std::mem::offset_of!(topform, normal_vars) - 93usize];
    ["Offset of field: topform::used"][::std::mem::offset_of!(topform, used) - 94usize];
    ["Offset of field: topform::official_id"]
        [::std::mem::offset_of!(topform, official_id) - 95usize];
    ["Offset of field: topform::initial"][::std::mem::offset_of!(topform, initial) - 96usize];
    ["Offset of field: topform::neg_compressed"]
        [::std::mem::offset_of!(topform, neg_compressed) - 97usize];
    ["Offset of field: topform::subsumer"][::std::mem::offset_of!(topform, subsumer) - 98usize];
    ["Offset of field: topform::was_given"][::std::mem::offset_of!(topform, was_given) - 99usize];
    ["Offset of field: topform::goal_derived"]
        [::std::mem::offset_of!(topform, goal_derived) - 100usize];
};
unsafe extern "C" {
    pub fn zap_topform(tf: Topform);
}
unsafe extern "C" {
    pub fn term_to_clause(t: Term) -> Topform;
}
unsafe extern "C" {
    pub fn topform_to_term_without_attributes(tf: Topform) -> Term;
}
unsafe extern "C" {
    pub fn renumber_variables(c: Topform, max_vars: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn copy_clause(c: Topform) -> Topform;
}
pub const Just_type_INPUT_JUST: Just_type = 0;
pub const Just_type_GOAL_JUST: Just_type = 1;
pub const Just_type_DENY_JUST: Just_type = 2;
pub const Just_type_CLAUSIFY_JUST: Just_type = 3;
pub const Just_type_COPY_JUST: Just_type = 4;
pub const Just_type_BACK_DEMOD_JUST: Just_type = 5;
pub const Just_type_BACK_UNIT_DEL_JUST: Just_type = 6;
pub const Just_type_NEW_SYMBOL_JUST: Just_type = 7;
pub const Just_type_EXPAND_DEF_JUST: Just_type = 8;
pub const Just_type_BINARY_RES_JUST: Just_type = 9;
pub const Just_type_HYPER_RES_JUST: Just_type = 10;
pub const Just_type_UR_RES_JUST: Just_type = 11;
pub const Just_type_FACTOR_JUST: Just_type = 12;
pub const Just_type_XXRES_JUST: Just_type = 13;
pub const Just_type_PARA_JUST: Just_type = 14;
pub const Just_type_PARA_FX_JUST: Just_type = 15;
pub const Just_type_PARA_IX_JUST: Just_type = 16;
pub const Just_type_PARA_FX_IX_JUST: Just_type = 17;
pub const Just_type_INSTANCE_JUST: Just_type = 18;
pub const Just_type_PROPOSITIONAL_JUST: Just_type = 19;
pub const Just_type_DEMOD_JUST: Just_type = 20;
pub const Just_type_UNIT_DEL_JUST: Just_type = 21;
pub const Just_type_FLIP_JUST: Just_type = 22;
pub const Just_type_XX_JUST: Just_type = 23;
pub const Just_type_MERGE_JUST: Just_type = 24;
pub const Just_type_EVAL_JUST: Just_type = 25;
pub const Just_type_IVY_JUST: Just_type = 26;
pub const Just_type_UNKNOWN_JUST: Just_type = 27;
pub type Just_type = ::std::os::raw::c_uint;
pub type Parajust = *mut parajust;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct parajust {
    pub from_id: ::std::os::raw::c_int,
    pub into_id: ::std::os::raw::c_int,
    pub from_pos: Ilist,
    pub into_pos: Ilist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of parajust"][::std::mem::size_of::<parajust>() - 24usize];
    ["Alignment of parajust"][::std::mem::align_of::<parajust>() - 8usize];
    ["Offset of field: parajust::from_id"][::std::mem::offset_of!(parajust, from_id) - 0usize];
    ["Offset of field: parajust::into_id"][::std::mem::offset_of!(parajust, into_id) - 4usize];
    ["Offset of field: parajust::from_pos"][::std::mem::offset_of!(parajust, from_pos) - 8usize];
    ["Offset of field: parajust::into_pos"][::std::mem::offset_of!(parajust, into_pos) - 16usize];
};
pub type Instancejust = *mut instancejust;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct instancejust {
    pub parent_id: ::std::os::raw::c_int,
    pub pairs: Plist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of instancejust"][::std::mem::size_of::<instancejust>() - 16usize];
    ["Alignment of instancejust"][::std::mem::align_of::<instancejust>() - 8usize];
    ["Offset of field: instancejust::parent_id"]
        [::std::mem::offset_of!(instancejust, parent_id) - 0usize];
    ["Offset of field: instancejust::pairs"][::std::mem::offset_of!(instancejust, pairs) - 8usize];
};
pub type Ivyjust = *mut ivyjust;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ivyjust {
    pub type_: Just_type,
    pub parent1: ::std::os::raw::c_int,
    pub parent2: ::std::os::raw::c_int,
    pub pos1: Ilist,
    pub pos2: Ilist,
    pub pairs: Plist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ivyjust"][::std::mem::size_of::<ivyjust>() - 40usize];
    ["Alignment of ivyjust"][::std::mem::align_of::<ivyjust>() - 8usize];
    ["Offset of field: ivyjust::type_"][::std::mem::offset_of!(ivyjust, type_) - 0usize];
    ["Offset of field: ivyjust::parent1"][::std::mem::offset_of!(ivyjust, parent1) - 4usize];
    ["Offset of field: ivyjust::parent2"][::std::mem::offset_of!(ivyjust, parent2) - 8usize];
    ["Offset of field: ivyjust::pos1"][::std::mem::offset_of!(ivyjust, pos1) - 16usize];
    ["Offset of field: ivyjust::pos2"][::std::mem::offset_of!(ivyjust, pos2) - 24usize];
    ["Offset of field: ivyjust::pairs"][::std::mem::offset_of!(ivyjust, pairs) - 32usize];
};
pub type Just = *mut just;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct just {
    pub type_: Just_type,
    pub next: Just,
    pub u: just__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union just__bindgen_ty_1 {
    pub id: ::std::os::raw::c_int,
    pub lst: Ilist,
    pub para: Parajust,
    pub demod: I3list,
    pub instance: Instancejust,
    pub ivy: Ivyjust,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of just__bindgen_ty_1"][::std::mem::size_of::<just__bindgen_ty_1>() - 8usize];
    ["Alignment of just__bindgen_ty_1"][::std::mem::align_of::<just__bindgen_ty_1>() - 8usize];
    ["Offset of field: just__bindgen_ty_1::id"]
        [::std::mem::offset_of!(just__bindgen_ty_1, id) - 0usize];
    ["Offset of field: just__bindgen_ty_1::lst"]
        [::std::mem::offset_of!(just__bindgen_ty_1, lst) - 0usize];
    ["Offset of field: just__bindgen_ty_1::para"]
        [::std::mem::offset_of!(just__bindgen_ty_1, para) - 0usize];
    ["Offset of field: just__bindgen_ty_1::demod"]
        [::std::mem::offset_of!(just__bindgen_ty_1, demod) - 0usize];
    ["Offset of field: just__bindgen_ty_1::instance"]
        [::std::mem::offset_of!(just__bindgen_ty_1, instance) - 0usize];
    ["Offset of field: just__bindgen_ty_1::ivy"]
        [::std::mem::offset_of!(just__bindgen_ty_1, ivy) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of just"][::std::mem::size_of::<just>() - 24usize];
    ["Alignment of just"][::std::mem::align_of::<just>() - 8usize];
    ["Offset of field: just::type_"][::std::mem::offset_of!(just, type_) - 0usize];
    ["Offset of field: just::next"][::std::mem::offset_of!(just, next) - 8usize];
    ["Offset of field: just::u"][::std::mem::offset_of!(just, u) - 16usize];
};
unsafe extern "C" {
    pub fn orient_equalities(c: Topform, allow_flips: BOOL);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fpa_index {
    _unused: [u8; 0],
}
pub type Fpa_index = *mut fpa_index;
pub const Mindextype_LINEAR: Mindextype = 0;
pub const Mindextype_FPA: Mindextype = 1;
pub const Mindextype_DISCRIM_WILD: Mindextype = 2;
pub const Mindextype_DISCRIM_BIND: Mindextype = 3;
pub type Mindextype = ::std::os::raw::c_uint;
pub const Uniftype_ORDINARY_UNIF: Uniftype = 0;
pub const Uniftype_BACKTRACK_UNIF: Uniftype = 1;
pub type Uniftype = ::std::os::raw::c_uint;
pub type Mindex = *mut mindex;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mindex {
    pub index_type: Mindextype,
    pub unif_type: Uniftype,
    pub fpa: Fpa_index,
    pub linear_first: Plist,
    pub linear_last: Plist,
    pub discrim_tree: Discrim,
    pub next: Mindex,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mindex"][::std::mem::size_of::<mindex>() - 48usize];
    ["Alignment of mindex"][::std::mem::align_of::<mindex>() - 8usize];
    ["Offset of field: mindex::index_type"][::std::mem::offset_of!(mindex, index_type) - 0usize];
    ["Offset of field: mindex::unif_type"][::std::mem::offset_of!(mindex, unif_type) - 4usize];
    ["Offset of field: mindex::fpa"][::std::mem::offset_of!(mindex, fpa) - 8usize];
    ["Offset of field: mindex::linear_first"]
        [::std::mem::offset_of!(mindex, linear_first) - 16usize];
    ["Offset of field: mindex::linear_last"][::std::mem::offset_of!(mindex, linear_last) - 24usize];
    ["Offset of field: mindex::discrim_tree"]
        [::std::mem::offset_of!(mindex, discrim_tree) - 32usize];
    ["Offset of field: mindex::next"][::std::mem::offset_of!(mindex, next) - 40usize];
};
unsafe extern "C" {
    pub fn mindex_init(
        mtype: Mindextype,
        utype: Uniftype,
        fpa_depth: ::std::os::raw::c_int,
    ) -> Mindex;
}
unsafe extern "C" {
    pub fn mindex_destroy(mdx: Mindex);
}
unsafe extern "C" {
    pub fn mindex_update(mdx: Mindex, t: Term, op: Indexop);
}
unsafe extern "C" {
    pub fn demodulator_type(
        c: Topform,
        lex_dep_demod_lim: ::std::os::raw::c_int,
        sane: BOOL,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn idx_demodulator(
        c: Topform,
        type_: ::std::os::raw::c_int,
        operation: Indexop,
        idx: Mindex,
    );
}
unsafe extern "C" {
    pub fn demod1(
        c: Topform,
        demodulator: Topform,
        direction: ::std::os::raw::c_int,
        fpos: *mut Ilist,
        ipos: *mut Ilist,
        lex_order_vars: BOOL,
    );
}
unsafe extern "C" {
    pub fn fdemod_clause(
        c: Topform,
        idx: Mindex,
        step_limit: *mut ::std::os::raw::c_int,
        increase_limit: *mut ::std::os::raw::c_int,
        lex_order_vars: BOOL,
    );
}
unsafe extern "C" {
    pub fn merge_literals(c: Topform);
}
unsafe extern "C" {
    pub fn resolve2(
        c1: Topform,
        n1: ::std::os::raw::c_int,
        c2: Topform,
        n2: ::std::os::raw::c_int,
        renumber_vars: BOOL,
    ) -> Topform;
}
unsafe extern "C" {
    pub fn xx_resolve2(c: Topform, n: ::std::os::raw::c_int, renumber_vars: BOOL) -> Topform;
}
unsafe extern "C" {
    pub fn subsumes(c: Topform, d: Topform) -> BOOL;
}
unsafe extern "C" {
    pub fn subsumes_bt(c: Topform, d: Topform) -> BOOL;
}
unsafe extern "C" {
    pub fn prover9_init();
}
unsafe extern "C" {
    pub fn prover9_term_is_variable(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_is_constant(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_is_complex(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_var_num(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_sym_num(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_arity(term: Term) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_term_symbol(term: Term) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn prover9_term_arg(term: Term, index: ::std::os::raw::c_int) -> Term;
}
unsafe extern "C" {
    pub fn prover9_term_set_arg(term: Term, index: ::std::os::raw::c_int, arg: Term);
}
unsafe extern "C" {
    pub fn prover9_max_vars() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_match(
        pattern: Term,
        context: Context,
        target: Term,
        trail: *mut Trail,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_literal_sign(literal: Literals) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_literal_atom(literal: Literals) -> Term;
}
unsafe extern "C" {
    pub fn prover9_topform_literals(topform: Topform) -> Literals;
}
unsafe extern "C" {
    pub fn prover9_context_binding_term(context: Context, varnum: ::std::os::raw::c_int) -> Term;
}
unsafe extern "C" {
    pub fn prover9_context_binding_context(
        context: Context,
        varnum: ::std::os::raw::c_int,
    ) -> Context;
}
unsafe extern "C" {
    pub fn prover9_can_demodulate(
        clause: Topform,
        demodulator: Topform,
        direction: ::std::os::raw::c_int,
        lex_order_vars: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_para_pos(
        from_clause: Topform,
        from_lit_num: ::std::os::raw::c_int,
        from_side: ::std::os::raw::c_int,
        into_clause: Topform,
        into_lit_num: ::std::os::raw::c_int,
        into_path: *const ::std::os::raw::c_int,
        into_path_len: ::std::os::raw::c_int,
        allow_into_vars: ::std::os::raw::c_int,
    ) -> Topform;
}
unsafe extern "C" {
    pub fn prover9_factor2(
        clause: Topform,
        lit1_num: ::std::os::raw::c_int,
        lit2_num: ::std::os::raw::c_int,
        renumber_vars: ::std::os::raw::c_int,
    ) -> Topform;
}
unsafe extern "C" {
    pub fn prover9_rewrite_index_new() -> Mindex;
}
unsafe extern "C" {
    pub fn prover9_rewrite_index_destroy(idx: Mindex);
}
unsafe extern "C" {
    pub fn prover9_rewrite_rule_type(clause: Topform) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_rewrite_prepare_rule(
        clause: Topform,
        allow_flips: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn prover9_rewrite_index_insert(
        rule: Topform,
        rule_type: ::std::os::raw::c_int,
        idx: Mindex,
    );
}
unsafe extern "C" {
    pub fn prover9_rewrite_index_remove(
        rule: Topform,
        rule_type: ::std::os::raw::c_int,
        idx: Mindex,
    );
}
unsafe extern "C" {
    pub fn prover9_rewrite_term(
        term: Term,
        idx: Mindex,
        lex_order_vars: ::std::os::raw::c_int,
    ) -> Term;
}
unsafe extern "C" {
    pub fn prover9_rewrite_clause(
        clause: Topform,
        idx: Mindex,
        lex_order_vars: ::std::os::raw::c_int,
    ) -> Topform;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clist_pos {
    pub _address: u8,
}
